version: "3.11"
services:
  postgres:
    image: postgres:15
    container_name: daac-db
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    container_name: web
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
